In [28]:
import numpy as np
import pandas as pd
import re                                  
import string  
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score
import torch
from torch.utils.data import TensorDataset, DataLoader, RandomSampler, SequentialSampler
from transformers import TrainingArguments, Trainer
from transformers import BertTokenizer, BertForSequenceClassification
from transformers import EarlyStoppingCallback
from transformers import BertModel, BertConfig

In [3]:
train_path = 'train.csv'

In [6]:
train_df = pd.read_csv(train_path)
train_df.head()

id                                       comment_text  toxic  \
0  0000997932d777bf  Explanation\nWhy the edits made under my usern...      0   
1  000103f0d9cfb60f  D'aww! He matches this background colour I'm s...      0   
2  000113f07ec002fd  Hey man, I'm really not trying to edit war. It...      0   
3  0001b41b1c6bb37e  "\nMore\nI can't make any real suggestions on ...      0   
4  0001d958c54c6e35  You, sir, are my hero. Any chance you remember...      0   

   severe_toxic  obscene  threat  insult  identity_hate  
0             0        0       0       0              0  
1             0        0       0       0              0  
2             0        0       0       0              0  
3             0        0       0       0              0  
4             0        0       0       0              0

In [7]:
def clean_text(text):
    text = text.lower()
    text = re.sub('\[.*?\]', '', text)
    text = re.sub('https?://\S+|www\.\S+', '', text)
    text = re.sub('<.*?>+', '', text)
    text = re.sub('[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub('\n', '', text)
    text = re.sub('\w*\d\w*', '', text)
    return text

In [8]:
train_df['comment_text'] = train_df['comment_text'].apply(lambda x: clean_text(x))
# train_df.head()

id                                       comment_text  toxic  \
0  0000997932d777bf  explanationwhy the edits made under my usernam...      0   
1  000103f0d9cfb60f  daww he matches this background colour im seem...      0   
2  000113f07ec002fd  hey man im really not trying to edit war its j...      0   
3  0001b41b1c6bb37e  morei cant make any real suggestions on improv...      0   
4  0001d958c54c6e35  you sir are my hero any chance you remember wh...      0   

   severe_toxic  obscene  threat  insult  identity_hate  
0             0        0       0       0              0  
1             0        0       0       0              0  
2             0        0       0       0              0  
3             0        0       0       0              0  
4             0        0       0       0              0

In [10]:
train_df.head(10)

id                                       comment_text  toxic  \
0  0000997932d777bf  explanationwhy the edits made under my usernam...      0   
1  000103f0d9cfb60f  daww he matches this background colour im seem...      0   
2  000113f07ec002fd  hey man im really not trying to edit war its j...      0   
3  0001b41b1c6bb37e  morei cant make any real suggestions on improv...      0   
4  0001d958c54c6e35  you sir are my hero any chance you remember wh...      0   
5  00025465d4725e87  congratulations from me as well use the tools ...      0   
6  0002bcb3da6cb337       cocksucker before you piss around on my work      1   
7  00031b1e95af7921  your vandalism to the matt shirvington article...      0   
8  00037261f536c51d  sorry if the word nonsense was offensive to yo...      0   
9  00040093b2687caa  alignment on this subject and which are contra...      0   

   severe_toxic  obscene  threat  insult  identity_hate  
0             0        0       0       0              0  
1             0        0       0       0              0  
2             0        0       0       0              0  
3             0        0       0       0              0  
4             0        0       0       0              0  
5             0        0       0       0              0  
6             1        1       0       1              0  
7             0        0       0       0              0  
8             0        0       0       0              0  
9             0        0       0       0              0

In [11]:
y= train_df.loc[:,'toxic':]
y.head()

toxic  severe_toxic  obscene  threat  insult  identity_hate
0      0             0        0       0       0              0
1      0             0        0       0       0              0
2      0             0        0       0       0              0
3      0             0        0       0       0              0
4      0             0        0       0       0              0

In [12]:
train_df.isna().sum()

id               0
comment_text     0
toxic            0
severe_toxic     0
obscene          0
threat           0
insult           0
identity_hate    0
dtype: int64

In [13]:
X = list(train_df['comment_text'])
y = np.array(train_df.loc[:,'toxic':])

In [15]:
y.shape

(159571, 6)

In [16]:
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.33, random_state=42)

In [17]:
print(X_train[0])
print(y_train[0])


sockpuppetry case you have been accused of sockpuppetry please refer to wikipediasockpuppet investigationspé de chinelo for evidence please make sure you make yourself familiar with notes for the suspect before editing the evidence page   
[0 0 0 0 0 0]


In [19]:
y_train

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       ...,
       [1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int64)

In [22]:
X_train[0]

'sockpuppetry case you have been accused of sockpuppetry please refer to wikipediasockpuppet investigationspé de chinelo for evidence please make sure you make yourself familiar with notes for the suspect before editing the evidence page   '

In [26]:
class BERTDataset:
    def __init__(self, texts, targets):
#         self.settings = Settings
        self.texts = texts
        self.targets = targets
        self.tokenizer = BertTokenizer.from_pretrained('bert-base-uncased',
                                                       do_lower_case=True)

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, item):
        sent = str(self.texts[item])
        inputs = self.tokenizer.encode_plus(
            text=sent,
            add_special_tokens=True,
            max_length=512,
            padding="max_length",
            return_attention_mask=True
        )

        ids = inputs["input_ids"]
        mask = inputs["attention_mask"]
        token_type_ids = inputs["token_type_ids"]

        return {
            'input_ids': torch.tensor(ids),
            'attention_mask': torch.tensor(mask),
            'token_type_ids': torch.tensor(token_type_ids),
            'targets': torch.tensor(self.targets[item])
        }

In [27]:
train_dataset = BERTDataset(X_train, y_train)

Downloading:   0%|          | 0.00/232k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/28.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/466k [00:00<?, ?B/s]

In [29]:
train_data_loader = DataLoader(train_dataset, batch_size=4)

In [34]:
for data in train_data_loader:
    print(data['input_ids'])
    print(data['targets'])
#   print(data['comment_text'].shape)
#   # print(data['target'])
#   print(data['comment_text'].view(-1))
    break

tensor([[  101, 28407, 14289,  ...,     0,     0,     0],
        [  101,  4921,  2063,  ...,     0,     0,     0],
        [  101, 16948,  2003,  ...,     0,     0,     0],
        [  101,  2107,  2004,  ...,     0,     0,     0]])
tensor([[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]])
